name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - 'APIJSON-Rust/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'APIJSON-Rust/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd UnitAuto-Rust && cargo build --verbose
    - name: Run tests
      run: cd UnitAuto-Rust && cargo test --verbose
